export enum PlanStatus {
  DRAFT = 'DRAFT',
  READY_FOR_REVIEW = 'READY_FOR_REVIEW',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REJECTED = 'REJECTED',
  RETURNED_FOR_CORRECTION = 'RETURNED_FOR_CORRECTION',
  APPROVED = 'APPROVED',
  ARCHIVED = 'ARCHIVED'
}
